data:
  descriptors_file: "data/descriptors.csv"
  concentrations_file: "data/components_fractions.csv"
  output_path: "data/processed/descriptors_combined.csv"

combinatorix:
  n_workers: 1
  threads_per_worker: 128
  memory_limit: "500GB"
  timeout: 300
  threshold_const: 0.01
  threshold_corr: 0.95
  batch_num: 100000

models_config = {
    'LinearRegression': {'type': 'LinearRegression'},
    'Lasso': {'type': 'Lasso', 'alpha': 1.0},
    'Ridge': {'type': 'Ridge', 'alpha': 1.0},
    'RandomForest_default': {'type': 'RandomForest', 'n_estimators': 100, 'random_state': 42},
    'RandomForest_simple': {'type': 'RandomForest', 'n_estimators': 50, 'max_depth': 3, 'random_state': 42},
    'DecisionTree_default': {'type': 'DecisionTree', 'random_state': 42},
    'DecisionTree_simple': {'type': 'DecisionTree', 'max_depth': 3, 'random_state': 42},
    'SVR_linear': {'type': 'SVR', 'kernel': 'linear'},
    'SVR_rbf': {'type': 'SVR', 'kernel': 'rbf'}
}

plots:
  save_dir: "outputs/plots/"
